const characters = [
    // === Alm’s Army ===
    { name: "Alm", path: "Alm", recruited: true, img: "media/portraits/Alm.png", startingClass: "Fighter", gender: "Male" },
    { name: "Lukas", path: "Alm", recruited: true, img: "media/portraits/Lukas.png", startingClass: "Soldier", gender: "Male" },
    { name: "Gray", path: "Alm", recruited: true, img: "media/portraits/Gray.png", startingClass: "Villager", gender: "Male" },
    { name: "Tobin", path: "Alm", recruited: true, img: "media/portraits/Tobin.png", startingClass: "Villager", gender: "Male" },
    { name: "Kliff", path: "Alm", recruited: true, img: "media/portraits/Kliff.png", startingClass: "Villager", gender: "Male" },
    { name: "Faye", path: "Alm", recruited: true, img: "media/portraits/Faye.png", startingClass: "Villager", gender: "Female" },
    { name: "Silque", path: "Alm", recruited: true, img: "media/portraits/Silque.png", startingClass: "Cleric", gender: "Female" },
    { name: "Clair", path: "Alm", recruited: true, img: "media/portraits/Clair.png", startingClass: "Pegasus Knight", gender: "Female" },
    { name: "Clive", path: "Alm", recruited: true, img: "media/portraits/Clive.png", startingClass: "Cavalier", gender: "Male" },
    { name: "Forsyth", path: "Alm", recruited: true, img: "media/portraits/Forsyth.png", startingClass: "Soldier", gender: "Male" },
    { name: "Python", path: "Alm", recruited: true, img: "media/portraits/Python.png", startingClass: "Archer", gender: "Male" },
    { name: "Luthier", path: "Alm", recruited: true, img: "media/portraits/Luthier.png", startingClass: "Mage", gender: "Male" },
    { name: "Mathilda", path: "Alm", recruited: true, img: "media/portraits/Mathilda.png", startingClass: "Paladin", gender: "Female" },
    { name: "Delthea", path: "Alm", recruited: true, img: "media/portraits/Delthea.png", startingClass: "Mage", gender: "Female" },
    { name: "Tatiana", path: "Alm", recruited: true, img: "media/portraits/Tatiana.png", startingClass: "Saint", gender: "Female" },
    { name: "Zeke", path: "Alm", recruited: true, img: "media/portraits/Zeke.png", startingClass: "Gold Knight", gender: "Male" },
    { name: "Mycen", path: "Alm", recruited: true, img: "media/portraits/Mycen.png", startingClass: "Gold Knight", gender: "Male" },

    // === Celica’s Army ===
    { name: "Celica", path: "Celica", recruited: true, img: "media/portraits/Celica.png", startingClass: "Priestess (Celica)", gender: "Female" },
    { name: "Mae", path: "Celica", recruited: true, img: "media/portraits/Mae.png", startingClass: "Mage", gender: "Female" },
    { name: "Boey", path: "Celica", recruited: true, img: "media/portraits/Boey.png", startingClass: "Mage", gender: "Male" },
    { name: "Genny", path: "Celica", recruited: true, img: "media/portraits/Genny.png", startingClass: "Cleric", gender: "Female" },
    { name: "Saber", path: "Celica", recruited: true, img: "media/portraits/Saber.png", startingClass: "Mercenary", gender: "Male" },
    { name: "Kamui", path: "Celica", recruited: true, img: "media/portraits/Kamui.png", startingClass: "Mercenary", gender: "Male" },
    { name: "Valbar", path: "Celica", recruited: true, img: "media/portraits/Valbar.png", startingClass: "Knight", gender: "Male" },
    { name: "Leon", path: "Celica", recruited: true, img: "media/portraits/Leon.png", startingClass: "Archer", gender: "Male" },
    { name: "Atlas", path: "Celica", recruited: true, img: "media/portraits/Atlas.png", startingClass: "Villager", gender: "Male" },
    { name: "Palla", path: "Celica", recruited: true, img: "media/portraits/Palla.png", startingClass: "Pegasus Knight", gender: "Female" },
    { name: "Catria", path: "Celica", recruited: true, img: "media/portraits/Catria.png", startingClass: "Pegasus Knight", gender: "Female" },
    { name: "Est", path: "Celica", recruited: true, img: "media/portraits/Est.png", startingClass: "Pegasus Knight", gender: "Female" },
    { name: "Jesse", path: "Celica", recruited: true, img: "media/portraits/Jesse.png", startingClass: "Mercenary", gender: "Male" },
    { name: "Sonya", path: "Celica", recruited: true, img: "media/portraits/Sonya.png", startingClass: "Mage", gender: "Female" },
    { name: "Deen", path: "Celica", recruited: true, img: "media/portraits/Deen.png", startingClass: "Myrmidon", gender: "Male" },
    { name: "Nomah", path: "Celica", recruited: true, img: "media/portraits/Nomah.png", startingClass: "Sage", gender: "Male" },
];
