const characters = [
    // === Alm’s Army ===
    { name: "Alm", path: "Alm", recruited: true, img: "media/portraits/Alm.png" },
    { name: "Lukas", path: "Alm", recruited: true, img: "media/portraits/Lukas.png" },
    { name: "Gray", path: "Alm", recruited: true, img: "media/portraits/Gray.png" },
    { name: "Tobin", path: "Alm", recruited: true, img: "media/portraits/Tobin.png" },
    { name: "Kliff", path: "Alm", recruited: true, img: "media/portraits/Kliff.png" },
    { name: "Faye", path: "Alm", recruited: true, img: "media/portraits/Faye.png" },
    { name: "Silque", path: "Alm", recruited: true, img: "media/portraits/Silque.png" },
    { name: "Clair", path: "Alm", recruited: true, img: "media/portraits/Clair.png" },
    { name: "Clive", path: "Alm", recruited: true, img: "media/portraits/Clive.png" },
    { name: "Forsyth", path: "Alm", recruited: true, img: "media/portraits/Forsyth.png" },
    { name: "Python", path: "Alm", recruited: true, img: "media/portraits/Python.png" },
    { name: "Luthier", path: "Alm", recruited: true, img: "media/portraits/Luthier.png" },
    { name: "Mathilda", path: "Alm", recruited: true, img: "media/portraits/Mathilda.png" },
    { name: "Delthea", path: "Alm", recruited: true, img: "media/portraits/Delthea.png" },
    { name: "Tatiana", path: "Alm", recruited: true, img: "media/portraits/Tatiana.png" },
    { name: "Zeke", path: "Alm", recruited: true, img: "media/portraits/Zeke.png" },
    { name: "Mycen", path: "Alm", recruited: true, img: "media/portraits/Mycen.png" },

    // === Celica’s Army ===
    { name: "Celica", path: "Celica", recruited: true, img: "media/portraits/Celica.png" },
    { name: "Mae", path: "Celica", recruited: true, img: "media/portraits/Mae.png" },
    { name: "Boey", path: "Celica", recruited: true, img: "media/portraits/Boey.png" },
    { name: "Genny", path: "Celica", recruited: true, img: "media/portraits/Genny.png" },
    { name: "Saber", path: "Celica", recruited: true, img: "media/portraits/Saber.png" },
    { name: "Kamui", path: "Celica", recruited: true, img: "media/portraits/Kamui.png" },
    { name: "Valbar", path: "Celica", recruited: true, img: "media/portraits/Valbar.png" },
    { name: "Leon", path: "Celica", recruited: true, img: "media/portraits/Leon.png" },
    { name: "Atlas", path: "Celica", recruited: true, img: "media/portraits/Atlas.png" },
    { name: "Palla", path: "Celica", recruited: true, img: "media/portraits/Palla.png" },
    { name: "Catria", path: "Celica", recruited: true, img: "media/portraits/Catria.png" },
    { name: "Est", path: "Celica", recruited: true, img: "media/portraits/Est.png" },
    { name: "Jesse", path: "Celica", recruited: true, img: "media/portraits/Jesse.png" },
    { name: "Sonya", path: "Celica", recruited: true, img: "media/portraits/Sonya.png" },
    { name: "Deen", path: "Celica", recruited: true, img: "media/portraits/Deen.png" },
    { name: "Nomah", path: "Celica", recruited: true, img: "media/portraits/Nomah.png" },
];
